### ISSUE TITLE
Add infrastructure for different "mains"

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/Smokescreen#61]
As we introduce new functionality like:
- Conceal DataVectors
- Encrypt/Decrypt Sacc files
- Conceal Posteriors
- etc

We want to be able to call `smokescreen` from the command line with different functionalities.

@stuartmcalpine has some examples which basically imply using this in the `pyproject.toml` file:
```toml
[project.scripts]
smokescreen = "smokescreen.__main__:alt_main"
```

Where the function `alt_main` is something like:
```python
def alt_main():
    CLI(main, as_positional=False)
```

This can be paired with `argparse` to have positional arguments to call each functionality.
